# Generated by Django 3.2.23 on 2023-12-09 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0008_sale_transaction_sales_item_salesorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sale_transaction',
            new_name='saleorder_transaction',
        ),
    ]
