# Generated by Django 3.2.23 on 2023-12-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0009_rename_sale_transaction_saleorder_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='adjustment',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='cgst',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='grandtotal',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='igst',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='paidoff',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='sgst',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='subtotal',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='total_taxamount',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='totalbalance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
