# Generated by Django 3.2.23 on 2023-12-09 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0010_auto_20231209_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billno', models.IntegerField(blank=True, default=0, null=True)),
                ('billdate', models.DateField()),
                ('duedate', models.DateField(blank=True, null=True)),
                ('pay_method', models.CharField(default='', max_length=255, null=True)),
                ('cheque_no', models.CharField(default='', max_length=255, null=True)),
                ('upi_no', models.CharField(default='', max_length=255, null=True)),
                ('balance', models.CharField(blank=True, max_length=255, null=True)),
                ('tot_bill_no', models.IntegerField(default=0, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.company')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.party')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.purchasebill')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.staff_details')),
            ],
        ),
    ]
