# Generated by Django 3.2.23 on 2023-12-11 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0011_paymentout'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOutHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('paymentout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.paymentout')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOutDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='paymentout_files/')),
                ('paymentout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.paymentout')),
            ],
        ),
    ]
