# Generated by Django 3.2.23 on 2023-12-13 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0013_deletedpaymentin_paymentin_paymentintransactionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallan',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.salesinvoice'),
        ),
    ]
