# Generated by Django 3.2.23 on 2023-12-19 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0017_paymentout_ref_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender_bank', models.TextField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('loan_amount', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('proccessing_fee', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('loan_received', models.CharField(blank=True, max_length=255, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('lr', models.CharField(blank=True, max_length=255, null=True)),
                ('balance_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('total_amount', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.company')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.party')),
            ],
        ),
        migrations.CreateModel(
            name='makepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('interest_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('total_amount', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('loan_received', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.loanaccounts')),
            ],
        ),
        migrations.CreateModel(
            name='LoanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('add', 'Add'), ('edit', 'Edit')], default='add', max_length=7)),
                ('loan_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.loanaccounts')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalLOan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_loan', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('interest_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('total_loan', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('loan_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.loanaccounts')),
                ('makepayment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.makepayment')),
            ],
        ),
    ]
