# Generated by Django 3.2.23 on 2023-12-20 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vyaparapp', '0019_auto_20231219_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retrn_no', models.IntegerField(blank=True, default=0, null=True)),
                ('partymob', models.CharField(blank=True, max_length=255, null=True)),
                ('invoiceno', models.CharField(blank=True, max_length=255, null=True)),
                ('supplyplace', models.CharField(default='', max_length=100)),
                ('pay_method', models.CharField(default='', max_length=255, null=True)),
                ('cheque_no', models.CharField(default='', max_length=255, null=True)),
                ('upi_no', models.CharField(default='', max_length=255, null=True)),
                ('bankaccount', models.CharField(default='', max_length=255, null=True)),
                ('subtotal', models.IntegerField(default=0, null=True)),
                ('igst', models.CharField(default=0, max_length=100, null=True)),
                ('cgst', models.CharField(default=0, max_length=100, null=True)),
                ('sgst', models.CharField(default=0, max_length=100, null=True)),
                ('taxamount', models.CharField(default=0, max_length=100, null=True)),
                ('adjust', models.CharField(default=0, max_length=100, null=True)),
                ('grandtotal', models.FloatField(default=0, null=True)),
                ('advance', models.CharField(blank=True, max_length=255, null=True)),
                ('balance', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_date', models.DateField()),
                ('date', models.DateField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('tot_credit_no', models.IntegerField(default=0, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.company')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.party')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.staff_details')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditNoteTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Created', 'Created'), ('Updated', 'Updated')], max_length=20)),
                ('transactiondate', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.company')),
                ('creditnote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.creditnote')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.staff_details')),
            ],
        ),
        migrations.CreateModel(
            name='CreditNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0, null=True)),
                ('rate', models.IntegerField(default=0, null=True)),
                ('total', models.IntegerField(default=0, null=True)),
                ('tax', models.CharField(max_length=100)),
                ('discount', models.CharField(default=0, max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.company')),
                ('creditnote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.creditnote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.itemmodel')),
            ],
        ),
    ]
