# Generated by Django 3.2.23 on 2023-12-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0021_auto_20231221_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='adjustment',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='subtotal',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
    ]
