# Generated by Django 3.2.23 on 2024-01-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0023_auto_20231226_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='invoice_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
