# Generated by Django 3.2.23 on 2024-01-10 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0024_alter_creditnote_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanhistory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.company'),
        ),
    ]
