# Generated by Django 3.2.23 on 2024-01-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0025_loanhistory_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='igst',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
