# Generated by Django 3.2.23 on 2024-01-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0026_expense_igst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_list',
            name='tax',
            field=models.CharField(max_length=255),
        ),
    ]
