# Generated by Django 3.2.23 on 2024-01-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0027_alter_expense_list_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='Cheque_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='expense',
            name='UPI_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
