# Generated by Django 3.2.23 on 2024-01-22 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0028_auto_20240112_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=255, null=True)),
                ('payment', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('interest_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('total_amount', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('loan_received', models.CharField(blank=True, max_length=255, null=True)),
                ('upi_id', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('cheque_number', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('balance_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.company')),
                ('loan_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.loanaccounts')),
            ],
        ),
    ]
