# Generated by Django 3.2.23 on 2024-01-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0030_admin_notification_company_notification_distributor_notification_payment_terms_updation'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Trial_action',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
