# Generated by Django 3.2.23 on 2024-01-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0031_company_trial_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Trial_Feedback',
            field=models.CharField(blank=True, default='Intrest', max_length=255, null=True),
        ),
    ]
