# Generated by Django 3.2.23 on 2024-01-25 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0032_company_trial_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanaccounts',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.staff_details'),
        ),
        migrations.AddField(
            model_name='loanhistory',
            name='Transaction_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.transactiontable'),
        ),
        migrations.AddField(
            model_name='loanhistory',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.staff_details'),
        ),
        migrations.AddField(
            model_name='transactiontable',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.staff_details'),
        ),
    ]
